// <auto-generated />
namespace OnlineTestRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removingquatitativesetidandtechnicalsetid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removingquatitativesetidandtechnicalsetid));
        
        string IMigrationMetadata.Id
        {
            get { return "201604260943279_removing quatitative set id and technical set id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
